name: build and test
on: push
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.6.0
          cache: 'yarn'
          cache-dependency-path: yarn.lock
      - run: yarn build
      - run: yarn lint
      - run: yarn test
